import { Challenge } from "./models";

export const CHALLENGES: Challenge[] = [
  {
    kind: "simple",
    id: "take_sips",
    text: "Take {n} sips",
    difficulty: "easy",
    quantity: { min: 1, max: 3 },
    categories: ["sips"],
    repeatability: "repeatable",
    cooldown: { globalTurns: 1, perPlayerTurns: 1 }, // default anyway, but explicit is ok
  },
  {
    kind: "simple",
    id: "give_sips",
    text: "Give {n} sips",
    difficulty: "easy",
    quantity: { min: 1, max: 3 },
    categories: ["sips", "social"],
  },
  {
    kind: "simple",
    id: "everyone_drinks",
    text: "Everyone drinks {n} sips",
    difficulty: "normal",
    quantity: { min: 1, max: 2 },
    categories: ["sips", "social"],
  },
  {
    kind: "tracked",
    id: "tracked_start_turn_drink",
    difficulty: "normal",
    action: "drink 1 sip at the start of your turn",
    rounds: { min: 2, max: 4 },
    categories: ["rule"],
  },
  {
    kind: "simple",
    id: "aji_cuchara",
    text: "Toma una cuchara de ají",
    difficulty: "brutal",
    categories: ["sips"],
  },
  {
    kind: "simple",
    id: "vinagre_aceite",
    text: "Bebe {n} churadas de vinagre o aceite",
    difficulty: "brutal",
    quantity: { min: 2, max: 2 },
    categories: ["sips"],
  },
  {
    kind: "simple",
    id: "al_seco",
    text: "Al seco, mi Rey/Reina",
    difficulty: "brutal",
    categories: ["sips"],
  },
  {
    kind: "simple",
    id: "bartender_shot",
    text: "Bartender! El de la derecha te prepara un shot con 3 ingredientes y debes tomarlo",
    difficulty: "brutal",
    categories: ["social", "sips"],
  },
  {
    kind: "simple",
    id: "misterio_shot",
    text: "Misterio? Toma un shot de un trago misterioso preparado por el resto",
    difficulty: "brutal",
    categories: ["sips"],
  },
  {
    kind: "simple",
    id: "companero_shot",
    text: "Busca a un compañero de copas para un shot, si nadie acepta toma {n} shots solo",
    difficulty: "brutal",
    quantity: { min: 2, max: 2 },
    categories: ["social", "sips"],
  },

  // ======================
  // MISC — SUPPORTED
  // ======================
  {
    kind: "simple",
    id: "ultimo_llega",
    text: "El último en llegar tómese un shot y una tapita para ponerse al día",
    difficulty: "normal",
    categories: ["social"],
    repeatability: "unique",
    cooldown: { globalTurns: 999, perPlayerTurns: 999, maxPerGame: 1 },
  },

  // ======================
  // HARD — SUPPORTED
  // ======================
  {
    kind: "simple",
    id: "cucharadas_licor",
    text: "Bebe {n} cucharadas de licor (desde la cuchara)",
    difficulty: "hard",
    quantity: { min: 3, max: 3 },
    categories: ["sips"],
  },
  {
    kind: "simple",
    id: "shot_sin_manos",
    text: "Toma un shot sin las manos o toma {n} shots",
    difficulty: "hard",
    quantity: { min: 2, max: 2 },
    categories: ["sips"],
  },
  {
    kind: "simple",
    id: "tres_sorbos",
    text: "Toma {n} sorbos seguidos",
    difficulty: "hard",
    quantity: { min: 3, max: 3 },
    categories: ["sips"],
  },
  {
    kind: "simple",
    id: "anecdota_vergonzosa",
    text: "Comparte una anécdota muy vergonzosa o bebe {n} sorbos",
    difficulty: "hard",
    quantity: { min: 4, max: 4 },
    categories: ["social"],
  },
  {
    kind: "simple",
    id: "imita_alguien",
    text: "Imita a alguien de la mesa. Si nadie lo adivina, bebes {n} sorbos",
    difficulty: "hard",
    quantity: { min: 3, max: 3 },
    categories: ["social"],
  },
  {
    kind: "simple",
    id: "dedo_erotico",
    text: "Chúpate el dedo con extremo erotismo",
    difficulty: "hard",
    categories: ["wildcard"],
  },

  // ======================
  // EASY / SIMPLE — SUPPORTED
  // ======================
  {
    kind: "simple",
    id: "vendedor",
    text: "Vendedor! Vende un producto al grupo (lo que sea)",
    difficulty: "easy",
    categories: ["social"],
  },
  {
    kind: "simple",
    id: "defiende_creencias",
    text: "Defiende tus creencias y da un discurso sobre por qué los hombres deben usar minifalda",
    difficulty: "easy",
    categories: ["social"],
  },
  {
    kind: "simple",
    id: "agua_salada",
    text: "Bebe un vaso de agua salada",
    difficulty: "easy",
    categories: ["sips"],
  },
  {
    kind: "simple",
    id: "propuesta_matrimonio",
    text: "Arrodíllate y pídele románticamente matrimonio al 2ndo más viejo",
    difficulty: "easy",
    categories: ["social"],
  },
  {
    kind: "simple",
    id: "si_no",
    text: "Responde {n} preguntas usando solo sí o no",
    difficulty: "easy",
    quantity: { min: 5, max: 5 },
    categories: ["social"],
  },
  {
    kind: "simple",
    id: "brindis_todos",
    text: "Salud! Haz un brindis, todos toman",
    difficulty: "easy",
    categories: ["social", "sips"],
  },
  {
    kind: "simple",
    id: "talento",
    text: "Demuestra un talento o toma {n}, si no tienes toma {m}",
    difficulty: "easy",
    categories: ["social"],
  },
  {
    kind: "simple",
    id: "mano_no_dominante",
    text: "Toma {n} sorbo con la mano no dominante",
    difficulty: "easy",
    quantity: { min: 1, max: 1 },
    categories: ["sips"],
  },
  {
    kind: "simple",
    id: "algo_bueno",
    text: "Di algo bueno del jugador de tu izquierda",
    difficulty: "easy",
    categories: ["social"],
  },
  {
    kind: "simple",
    id: "brindis_alguien",
    text: "Haz un brindis por alguien en la mesa",
    difficulty: "easy",
    categories: ["social"],
  },
  {
    kind: "simple",
    id: "mejor_vestido",
    text: "Pero qué belleza! El mejor vestido toma {n} sorbos",
    difficulty: "easy",
    quantity: { min: 4, max: 4 },
    categories: ["social"],
  },
  {
    kind: "simple",
    id: "peor_vestido",
    text: "La persona peor vestida toma {n} sorbos",
    difficulty: "easy",
    quantity: { min: 2, max: 2 },
    categories: ["social"],
  },

  // ======================
  // TRACKED RULES — SUPPORTED
  // ======================
  {
    kind: "tracked",
    id: "hablar_pregunta",
    action: "hablar solo en forma de pregunta",
    rounds: { min: 2, max: 4 },
    difficulty: "normal",
    categories: ["rule"],
  },
  {
    kind: "tracked",
    id: "no_nombres",
    action: "no decir nombres propios",
    rounds: { min: 2, max: 4 },
    difficulty: "normal",
    categories: ["rule"],
  },
  {
    kind: "tracked",
    id: "no_si_no",
    action: "no decir sí ni no",
    rounds: { min: 2, max: 4 },
    difficulty: "normal",
    categories: ["rule"],
  },
  {
    kind: "tracked",
    id: "acento_exagerado",
    action: "hablar con acento exagerado",
    rounds: { min: 2, max: 4 },
    difficulty: "normal",
    categories: ["rule"],
  },
  {
    kind: "tracked",
    id: "una_silaba",
    action: "usar solo una sílaba por palabra",
    rounds: { min: 2, max: 4 },
    difficulty: "hard",
    categories: ["rule"],
  },
  {
    kind: "tracked",
    id: "no_apuntar",
    action: "no apuntar con el dedo, solo con la mirada",
    rounds: { min: 2, max: 4 },
    difficulty: "normal",
    categories: ["rule"],
  },
  {
    kind: "simple",
    id: "botella_prenda",
    text: "Gira una botella y cambia una prenda con la persona en la que caiga o ambos toman {n}",
    difficulty: "hard",
    quantity: { min: 4, max: 4 },
    categories: ["social", "wildcard"],
  },
  {
    kind: "simple",
    id: "botella_beso_cachete",
    text: "Gira una botella, en quien caiga bésalo o cachetéalo o toma {n}",
    difficulty: "hard",
    quantity: { min: 2, max: 2 },
    categories: ["social", "wildcard"],
  },
  {
    kind: "simple",
    id: "piscina",
    text: "Salta a una piscina o toma un shot",
    difficulty: "hard",
    categories: ["wildcard"],
  },
  {
    kind: "simple",
    id: "carta_alta",
    text: "Carta Alta",
    difficulty: "normal",
    categories: ["minigame"],
  },
  {
    kind: "simple",
    id: "copa_del_rey",
    text: "Copa del Rey: el que la llene, se la toma",
    difficulty: "normal",
    categories: ["social", "rule"],
  },

  // ======================
  // PLAYER-ENFORCED RULES (TRACKED)
  // ======================
  {
    kind: "tracked",
    id: "esclavo",
    action: "obedecer a un compañero de copas elegido",
    rounds: { min: 2, max: 4 },
    difficulty: "normal",
    categories: ["rule", "social"],
  },
  {
    kind: "tracked",
    id: "regla_global",
    action: "cumplir una regla impuesta por un jugador",
    rounds: { min: 2, max: 4 },
    difficulty: "normal",
    categories: ["rule"],
  },
  {
    kind: "tracked",
    id: "virus_regla",
    action: "cumplir una regla impuesta por otro jugador",
    rounds: { min: 2, max: 4 },
    difficulty: "hard",
    categories: ["rule"],
  },
  {
    kind: "tracked",
    id: "mano_suelo",
    action: "mantener al menos una mano en el suelo",
    rounds: { min: 1, max: 1 },
    difficulty: "hard",
    categories: ["rule"],
  },

  // ======================
  // TRACKED — PREVIOUSLY SKIPPED (NOW ADDED)
  // ======================
  {
    kind: "tracked",
    id: "no_pestanear",
    action: "no pestañear hasta tu siguiente turno",
    rounds: { min: 1, max: 1 },
    difficulty: "hard",
    categories: ["rule"],
  },
  {
    kind: "tracked",
    id: "sin_polera",
    action: "estar sin polera hasta tu siguiente turno",
    rounds: { min: 1, max: 1 },
    difficulty: "hard",
    categories: ["rule", "social"],
  },
  {
    kind: "tracked",
    id: "no_hablar",
    action: "comunicarte sin hablar",
    rounds: { min: 2, max: 2 },
    difficulty: "normal",
    categories: ["rule"],
  },
  {
    kind: "tracked",
    id: "hablar_raro",
    action: "hablar de forma exagerada hasta la próxima ronda",
    rounds: { min: 1, max: 1 },
    difficulty: "easy",
    categories: ["rule"],
  },
  {
    kind: "simple",
    id: "quien_es_mas_probable",
    text: "¿Quién es más probable? Todos apuntan. El más votado toma {n} sorbos",
    difficulty: "normal",
    quantity: { min: 2, max: 4 },
    categories: ["social", "minigame"],
  },
  {
    kind: "simple",
    id: "carrera_caracoles",
    text: "Carrera de caracoles: elige tu caracol y hagan la carrera. El perdedor toma {n} sorbos",
    difficulty: "normal",
    quantity: { min: 2, max: 4 },
    categories: ["minigame", "social"],
  },
  {
    kind: "simple",
    id: "cascada",
    text: "Cascada: comiencen a tomar en cadena. Nadie puede parar hasta que la persona anterior pare. El que rompa la cascada toma {n} sorbos",
    difficulty: "hard",
    quantity: { min: 2, max: 5 },
    categories: ["minigame", "sips", "social"],
  },

  // Ritual / category prompt (simple)
  {
    kind: "simple",
    id: "cultura_chupistica_pide",
    text: "La cultura chupística pide: inventen una tradición/ritual ahora. Si alguien se niega, toma {n} sorbos",
    difficulty: "easy",
    quantity: { min: 2, max: 3 },
    categories: ["social", "wildcard"],
  },
  {
    kind: "simple",
    id: "no_tocar_telefono",
    text: "dejar tu teléfono en la mesa y no tocarlo",
    difficulty: "normal",
    categories: ["minigame"],
  },
  {
    kind: "simple",
    id: "entrevista_trabajo",
    text: "Entrevista de trabajo: el jugador delante tuyo te entrevistará para ser actor porno. Si te rechazan, toma {n} sorbos",
    difficulty: "easy",
    quantity: { min: 3, max: 4 },
    categories: ["social"],
  },

  {
    kind: "simple",
    id: "derecha_reto_castigo",
    text: "El de la derecha puede darte el reto que quiera. Si no aceptas, el resto elige el castigo",
    difficulty: "brutal",
    categories: ["social", "wildcard"],
  },

  {
    kind: "simple",
    id: "hora_de_rezar",
    text: "Hora de rezar! Ponte en tus rodillas, abre tu boca y un jugador deberá darte un shot desde 25cm de distancia",
    difficulty: "brutal",
    categories: ["social", "wildcard"],
    repeatability: "annoying",
    cooldown: { globalTurns: 2, perPlayerTurns: 2, maxPerGame: 3 },
  },
];
